service: contact-backend

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: python3.7

# you can overwrite defaults here
#  stage: dev
  region: us-east-1

# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
      Resource: ${opt:identity_arn}

# you can define service wide environment variables here
  environment:
    SENDING_ADDRESS: ${opt:sending_address}
    RECEIVING_ADDRESSES: ${opt:receiving_addresses}

# you can add packaging information here
package:
  include:
    - config.py
    - handler.py
  exclude:
    - Makefile
    - tests.py
    - .autoenv
    - requirements.dev.txt
    - __pycache__
    - .venv
    - .vscode
    - .pytest_cache

functions:
  handle_contact:
    handler: handler.handle_contact
#    The following are a few example events you can configure
#    NOTE: Please make sure to change your handler code to work with those events
#    Check the event documentation for details
    events:
      - http:
          path: contacts
          method: post

#    Define function environment variables here
#    environment:
#      variable2: value2

plugins:
  - serverless-python-requirements
